EHOINET_VERSION: 1
AUG:
  RANDOM_CONTRAST_MIN: 0.8
  RANDOM_CONTRAST_MAX: 1.5
  RANDOM_BRIGHTNESS_MIN: 0.8
  RANDOM_BRIGHTNESS_MAX: 1.3
  RANDOM_LIGHTING_SCALE: 0.1
ADDITIONAL_MODULES:
  ASSOCIATION_VECTOR_REGRESSOR_MODULE_DROPOUT: 0.0
  ASSOCIATION_VECTOR_SCALE_FACTOR: 1
  CONTACT_STATE_CLASSIFICATION_MODULE_DROPOUT: 0.3
  CONTACT_STATE_MODALITY: "rgb"
  CONTACT_STATE_CNN_INPUT_SIZE: 128
  SIDE_LR_CLASSIFICATION_MODULE_DROPOUT: 0.3
  USE_MASK: False
  USE_MASK_GT: False
  KEYPOINTS: False
  KEYPOINTS_GT: False
  THRESH_OBJS: 0.5
  NMS_THRESH: 1
  EXPAND_HAND_BOX_RATIO: 0.3
  DEPTH_MODULE:
    USE_DEPTH_MODULE: False
    NET_W: 384
    NET_H: 384
    RESIZE_MODE: "upper_bound"
    WEIGHT_LOSS: 1
    FEATURES: 256
    NON_NEGATIVE: True
    WEIGHT_PATH: null
    PRETRAIN: False
    LR: 1e-05
DATASETS:
  RANDOM_FLIP: null
MODEL:
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 21
UTILS:
  TARGET_SHAPE_H: 720
  TARGET_SHAPE_W: 1280
  VISUALIZER:
    THRESH_OBJS: 0.5
    DRAW_EHOI: True
    DRAW_MASK: True
    DRAW_OBJS: True
    DRAW_KEYPOINTS: True
    DRAW_DEPTH: True
VERSION: 2